<Project Sdk="Aspire.AppHost.Sdk/13.2.2">

  <ItemGroup>
    <ProjectReference Include="..\Api\RangeExtendedEvDigitalTwin.Api.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.JavaScript" Version="13.2.2" />
    <PackageReference Include="Aspire.Hosting.PostgreSQL" Version="13.2.2" />
    <PackageReference Include="Aspire.Hosting.RabbitMQ" Version="13.2.2" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>1c988eaa-995b-4f85-a8e9-07f35dc9704a</UserSecretsId>
  </PropertyGroup>

</Project>
